image: docker

services:
  - docker:dind

before_script:
  - apk update
  - export
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

app-test:
  image: node:latest
  cache:
    paths:
      - node_modules/
  script:
    - npm install
    - npm run test

build:
  script:
    - docker pull registry.gitlab.com/viktor0018/skillbox:latest
    - docker build --cache-from registry.gitlab.com/viktor0018/skillbox --tag registry.gitlab.com/viktor0018/skillbox:$CI_BUILD_REF --tag registry.gitlab.com/viktor0018/skillbox:latest .
    - docker push registry.gitlab.com/viktor0018/skillbox:$CI_BUILD_REF
    - docker push registry.gitlab.com/viktor0018/skillbox:latest
